# Generated by Django 5.2 on 2025-04-25 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('health_program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('insurance_code', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to='doctor.doctorprofile')),
                ('health_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_program.healthprogram')),
            ],
        ),
    ]
